### ISSUE TITLE
how to solve the below problem?

### ISSUE THREAD

**Issue by SGXC33** [Wenchao-Du/GAENet#1]
when i run the 'train.py',the error is occured,can you tell me how to solve the following problem?

2022-07-01 15:57:54
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/root/GAENet-main/train.py", line 56, in <module>
    main()
  File "/root/GAENet-main/train.py", line 40, in main
    train(config, 0)
  File "/root/GAENet-main/trainer.py", line 156, in train
    for i, inputs in tqdm(enumerate(train_loader)):
  File "/root/.local/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/GAENet-main/nyuv2_dataset/dataloader.py", line 155, in __getitem__
    rgb_np, depth_np = self.transform(rgb, depth)
  File "/root/GAENet-main/nyuv2_dataset/nyu_dataloader.py", line 37, in train_transform
    rgb_np = transform(rgb)
  File "/root/GAENet-main/nyuv2_dataset/transforms.py", line 195, in __call__
    img = t(img)
  File "/root/GAENet-main/nyuv2_dataset/transforms.py", line 344, in __call__
    return resize(img, self.size, self.interpolation)
  File "/root/.local/lib/python3.9/site-packages/skimage/transform/_warps.py", line 145, in resize
    image, output_shape = _preprocess_resize_output_shape(image, output_shape)
  File "/root/.local/lib/python3.9/site-packages/skimage/transform/_warps.py", line 55, in _preprocess_resize_output_shape
    output_shape = tuple(output_shape)
TypeError: 'float' object is not iterable

**Comment by Wenchao-Du** [comment]
you should prepare your training data in the correct format @SGXC33
